directives:

# Add iiwa
- add_model:
    name: point
    file: package://combining_kinematics/models/global_ik_iiwa/point_robot.sdf
    default_joint_positions:
        x_joint: [0]
        y_joint: [0]
        z_joint: [0]

- add_weld:
    parent: world
    child: point::body


# Add bins
# - add_model:
#     name: binR
#     # file: package://drake/examples/manipulation_station/models/bin2.sdf
#     file: package://drake_models/manipulation_station/bin2.sdf

# - add_weld:
#     parent: world
#     child: binR::bin_base
#     X_PC:
#       translation: [-0.42, -0.57, 0]
#       rotation: !Rpy { deg: [0.0, 0.0, 45.0 ]}
      

# - add_model:
#     name: binL
#     # file: package://drake/examples/manipulation_station/models/bin2.sdf
#     file: package://drake_models/manipulation_station/bin2.sdf

# - add_weld:
#     parent: world
#     child: binL::bin_base
#     X_PC:
#       translation: [-0.42, 0.57, 0]
#       rotation: !Rpy { deg: [0.0, 0.0, 135.0 ]}


- add_model:
    name: binF
    # file: package://drake/examples/manipulation_station/models/bin2.sdf
    file: package://drake_models/manipulation_station/bin2.sdf

- add_weld:
    parent: world
    child: binF::bin_base
    X_PC:
      translation: [0.75, 0, 0]
      rotation: !Rpy { deg: [0.0, 0.0, 0.0 ]}




# Add table
- add_model:
    name: table
    # file: package://drake/examples/manipulation_station/models/table_wide.sdf
    file: package://drake_models/manipulation_station/table_wide.sdf

- add_weld:
    parent: world
    child: table::table_body
    X_PC:
      translation: [0.4, 0.0, 0.0]

# Add table
- add_model:
    name: table2
    # file: package://drake/examples/manipulation_station/models/table_wide.sdf
    file: package://drake_models/manipulation_station/table_wide.sdf

- add_weld:
    parent: world
    child: table2::table_body
    X_PC:
      translation: [-0.2, 0.0, 0.0]



# Add shelves
- add_model:
    name: shelves
    # file: package://drake/examples/manipulation_station/models/shelves.sdf
    file: package://combining_kinematics/models/assets/shelves.sdf

- add_weld:
    parent: world
    child: shelves::shelves_body
    X_PC:
      translation: [0.3, 0.55, 0.4]
      rotation: !Rpy { deg: [0.0, 0.0, 235.0 ]}



# Add shelves
- add_model:
    name: shelves2
    # file: package://drake/examples/manipulation_station/models/shelves.sdf
    file: package://combining_kinematics/models/assets/shelves.sdf
    # file: package://drake_models/manipulation_station/shelves.sdf

- add_weld:
    parent: world
    child: shelves2::shelves_body
    X_PC:
      translation: [0.3, -0.55, 0.4]
      rotation: !Rpy { deg: [0.0, 0.0, 135.0 ]}


- add_model:
    name: shelves3
    # file: package://drake/examples/manipulation_station/models/shelves.sdf
    file: package://combining_kinematics/models/assets/shelves.sdf

- add_weld:
    parent: world
    child: shelves3::shelves_body
    X_PC:
      translation: [-0.45, -0.55, 0.4]
      rotation: !Rpy { deg: [0.0, 0.0, 235.0 ]}



# Add shelves
- add_model:
    name: shelves4
    # file: package://drake/examples/manipulation_station/models/shelves.sdf
    file: package://combining_kinematics/models/assets/shelves.sdf
    # file: package://drake_models/manipulation_station/shelves.sdf

- add_weld:
    parent: world
    child: shelves4::shelves_body
    X_PC:
      translation: [-0.45, 0.55, 0.4]
      rotation: !Rpy { deg: [0.0, 0.0, 135.0 ]}

